name: CD

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    if: ${{ github.event.head_commit.committer.name != 'Versioning Action' }}
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.KEY }}

      - name: Bump version
        uses: tool3/bump@master
        id: bump
        with:
          github_token: ${{ secrets.KEY }}
          user: 'Versioning Action'
          email: 'versioning@github.com'
          branch: 'main'

      - name: Build Docker images
        run: docker build --tag michaeljolley/twitch-orbit:${{ steps.bump.outputs.version }} --tag michaeljolley/twitch-orbit:latest .

      - name: Login to Docker Hub
        if: success()
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

      - name: Push :latest tag to Docker Hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push michaeljolley/twitch-orbit:latest
          
      - name: Push version tag to Docker Hub
        if: success()
        uses: actions-hub/docker@master
        with:
          args: push michaeljolley/twitch-orbit:${{ steps.bump.outputs.version }}